// $ANTLR 2.7.6 (2005-12-22): "Predicat.g" -> "PredicatLexer.java"$

    package ABTOOLS.GRAMMAR;
    
    import ABTOOLS.DEBUGGING.*;
    import ABTOOLS.ANTLR_TOOLS.*;

public interface PredicatTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int B_LPAREN = 4;
	int B_COMMA = 5;
	int B_RPAREN = 6;
	int B_PARALLEL = 7;
	int B_DOUBLE_EQUAL = 8;
	int B_MINUS = 9;
	int B_ADD = 10;
	int B_POWER = 11;
	int B_MULT = 12;
	int B_DIV = 13;
	int B_AND = 14;
	int B_dollars = 15;
	int B_OUT = 16;
	int B_garde = 17;
	int B_SEMICOLON = 18;
	int B_BECOME_ELEM = 19;
	int B_SIMPLESUBST = 20;
	int B_IMPLIES = 21;
	int B_EQUIV = 22;
	int B_INSET = 23;
	int B_NOTINSET = 24;
	int B_SUBSET = 25;
	int B_NOTSUBSET = 26;
	int B_STRICTSUBSET = 27;
	int B_NOTSTRICTSBSET = 28;
	int B_EMPTYSET = 29;
	int B_CURLYOPEN = 30;
	int B_CURLYCLOSE = 31;
	int B_EQUAL = 32;
	int B_LESS = 33;
	int B_GREATER = 34;
	int B_NOTEQUAL = 35;
	int B_LESSTHANEQUAL = 36;
	int B_GREATERTHANEQUAL = 37;
	int B_PARTIAL = 38;
	int B_RELATION = 39;
	int B_TOTAL = 40;
	int B_PARTIAL_INJECT = 41;
	int B_TOTAL_INJECT = 42;
	int B_PARTIAL_SURJECT = 43;
	int B_TOTAL_SURJECT = 44;
	int B_BIJECTION = 45;
	int B_TILDE = 46;
	int B_BRACKOPEN = 47;
	int B_BRACKCLOSE = 48;
	int B_QUOTEIDENT = 49;
	int B_MAPLET = 50;
	int B_DOMAINRESTRICT = 51;
	int B_RANGERESTRICT = 52;
	int B_DOMAINSUBSTRACT = 53;
	int B_RANGESUBSTRACT = 54;
	int B_OVERRIDEFORWARD = 55;
	int B_OVERRIDEBACKWARD = 56;
	int B_RELPROD = 57;
	int B_CONCATSEQ = 58;
	int B_PREAPPSEQ = 59;
	int B_APPSEQ = 60;
	int B_PREFIXSEQ = 61;
	int B_SUFFIXSEQ = 62;
	int B_RANGE = 63;
	int B_UNION = 64;
	int B_INTER = 65;
	int B_LAMBDA = 66;
	int B_FORALL = 67;
	int B_EXISTS = 68;
	int B_SEQEMPTY = 69;
	int B_POINT = 70;
	int B_SUCH = 71;
	int B_CPRED = 72;
	int DIGIT = 73;
	int B_NUMBER = 74;
	int ALPHA = 75;
	int B_ASTRING = 76;
	int VOCAB = 77;
	int B_IDENTIFIER = 78;
	int WS = 79;
	int ML_COMMENT = 80;
}
